version: '3.7'

services:

  benovate:
    image: osminogin/benovate
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://postgres:postgres@postgres/postgres
    ports:
      - 9000:9000
    depends_on:
      - postgres

  postgres:
    image: postgres:11-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-data:
