version: '3.7'

services:

  benovate:
    image: osminogin/benovate
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/postgres
    ports:
      - 9000:9000

  postgres:
    image: postgres:11-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      restart_policy:
        delay: 30s
        max_attempts: 10
        window: 60s

volumes:
  postgres-data:
