# Generated by Django 2.2 on 2019-04-14 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txs', '0002_auto_20190413_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='recipients',
            field=models.ManyToManyField(related_name='recipients', to=settings.AUTH_USER_MODEL),
        ),
    ]
